spring.application.name=backend-politicas

server.port=8080

spring.mongodb.uri=mongodb://localhost:27017/politicas_negocio

servicio.ia.url=http://localhost:8000

notificaciones.firebase.habilitadas=false