spring.application.name=BACKEND_POLITICAS

server.port=8080

spring.mongodb.uri=mongodb://localhost:27017/politicas_negocio

servicio.ia.url=http://localhost:8000

notificaciones.firebase.habilitadas=true
notificaciones.firebase.ruta-credenciales=firebase/firebase-service-account.json