package com.politicasnegocio.backendpoliticas.enumeracion;

public enum EstadoTramite {
    NUEVO,
    REGISTRADO,
    RECIBIDO,
    EN_REVISION,
    EN_EVALUACION,
    EN_ESPERA_DE_DOCUMENTOS,
    DOCUMENTACION_OBSERVADA,
    DOCUMENTACION_CORREGIDA,
    DERIVADO_A_OTRO_DEPARTAMENTO,
    EN_ATENCION,
    EN_PROCESO,
    EN_REVISION_LEGAL,
    EN_REVISION_ADMINISTRATIVA,
    EN_REVISION_DE_ALMACEN,
    OBSERVADO,
    PENDIENTE,
    PAUSADO,
    RECHAZADO,
    APROBADO,
    COMPLETADO,
    FINALIZADO,
    ARCHIVADO
}